image: node:latest

stages:
  - setup
  - test
  - build

setup:
  stage: setup
  script: ['npm install']

test:common:
  stage: test
  script: ['gulp common:test']

test:chrome:
  stage: test
  script: ['gulp chrome:js:test']

build:chrome:
  stage: build
  script: ['gulp']
  artifacts:
    paths: ['build/chrome']
